# Generated by Django 4.2.30 on 2026-07-07 08:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("payee", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")], max_length=15
                    ),
                ),
                ("avg_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cadence_days", models.PositiveIntegerField()),
                ("next_expected_at", models.DateField()),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=3)),
                ("last_matched_at", models.DateField()),
                ("sample_count", models.PositiveIntegerField()),
                ("is_dismissed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_rules",
                        to="finance.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_rules",
                        to="finance.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring rule",
                "verbose_name_plural": "Recurring rules",
                "db_table": "recurring_rules",
                "ordering": ("next_expected_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="recurringrule",
            constraint=models.UniqueConstraint(
                fields=("user", "account", "payee", "kind"),
                name="uniq_recurring_per_user_account_payee_kind",
            ),
        ),
    ]
